#!/usr/bin/env bash

set -e
#set -x


if [ "$#" -lt 1 ]
then
	echo "usage error: config argument required"
	exit 1
fi


watch_patterns="*.py;*.ini"

sapyens_path="../sapyens"
if [ -d "$sapyens_path" ]; then
	extra_dirs=--directory\ "$sapyens_path"
fi

ignore_patterns=--ignore-patterns\ "venv"


watchmedo auto-restart \
	--patterns $watch_patterns \
	$ignore_patterns \
	--directory . \
	$extra_dirs \
	--recursive \
	gunicorn -- --paste "$@"
